### PR TITLE
Add a missing word and make spelling changes

### PR DESCRIPTION
**Pull request by donaldali**
Add 'have' to 'If you any trouble...' making it 'If you have any trouble...'.
Change 'Github' to 'GitHub'.
Change 'resume' to 'résumé'.

### CODE REVIEW

**Comment by adarsh** [comment]
:four_leaf_clover::church::four::sunrise_over_mountains::taxi:

**Comment by donaldali** [comment]
I'm sorry but I didn't understand your last comment

**Comment by adarsh** [comment]
Comment means "Looks good to me" :+1:

**Comment by donaldali** [comment]
Thanks

**Pull request merged**
